version: '2.0'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3333:3306

  mongo:
    restart: always
    image: mongo
    volumes:
      - ./db-data:/data/db
    ports:
      - 27018:27017
  redis:
    restart: always
    image: redis
    volumes:
      - ./redis-conf:/usr/local/etc/redis.conf
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
